### ISSUE TITLE
'count' or 'for_each' with module breaks package.py 

### ISSUE THREAD

**Issue by okgolove** [terraform-aws-modules/terraform-aws-notify-slack#116]
### Steps to reproduce:
1. Try to create multiple notifiers using `for_each`:
```
module "notify_slack" {
  for_each = toset([
    "builds-develop",
    "builds-release",
    "builds-misc"
  ])

  source  = "terraform-aws-modules/notify-slack/aws"
  version = "~> 4.0"

  lambda_function_name = "${each.key}-slack"
  sns_topic_name       = "${each.key}-slack"
  slack_webhook_url    = "https://coolurl"
  slack_channel        = each.key
  slack_username       = "Jenkins"
}
```

### Expected behaviour:
3 sets of lambda and sns have been created

### Actual result:
Terraform fails with error:
```
Error: failed to execute "python3": Traceback (most recent call last):
  File ".terraform/modules/notify_slack.lambda/package.py", line 1228, in <module>
    main()
  File ".terraform/modules/notify_slack.lambda/package.py", line 1224, in main
    exit(args.command(args))
  File ".terraform/modules/notify_slack.lambda/package.py", line 1068, in prepare_command
    os.makedirs(artifacts_dir)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: 'builds'




Error: failed to execute "python3": Traceback (most recent call last):
  File ".terraform/modules/notify_slack.lambda/package.py", line 1228, in <module>
    main()
  File ".terraform/modules/notify_slack.lambda/package.py", line 1224, in main
    exit(args.command(args))
  File ".terraform/modules/notify_slack.lambda/package.py", line 1068, in prepare_command
    os.makedirs(artifacts_dir)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: 'builds'
```

There is a variable in the lamda module called [artifacts_dir](https://github.com/terraform-aws-modules/terraform-aws-lambda/blob/master/variables.tf#L450). May be we should be able to modify the variable.

**Comment by antonbabenko** [comment]
Hi @okgolove !

The problem was in the Lambda module, which was fixed a couple of weeks ago but this module was not updated after that.

I will take a look into this now.

**Comment by antonbabenko** [comment]
Please try to use code from the branch "ci-pre-commit" (ref #117).

It will require the recreation of lambda functions because the hash function has changed.

**Comment by okgolove** [comment]
@antonbabenko thank you, now it works with for_each.

**Comment by antonbabenko** [comment]
Good, thanks for the feedback and support!

[v4.6.0](https://github.com/terraform-aws-modules/terraform-aws-notify-slack/releases/v4.6.0) has been just released.
