### ISSUE TITLE
FileNotFoundError when creating module instance

### ISSUE THREAD

**Issue by vdmkenny** [terraform-aws-modules/terraform-aws-notify-slack#120]
# Setup

Terraform version: `0.13.5`
Module version: `4.7.0`
module "notify_slack" used according to the basic example

In the "apply" stage for terraform, I get this output. Mind you, the module actually seems to work correctly.
I have messages arriving in slack.

What is this error relating to? My terraform pipeline stays red because of this...

```
module.notify_slack["my_app"].module.lambda.null_resource.archive[0]: Destroying... [id=8360185324643769328]
module.notify_slack["my_app"].module.lambda.null_resource.archive[0]: Destruction complete after 0s
module.notify_slack["my_app"].module.lambda.data.external.archive_prepare[0]: Reading... [id=-]
module.notify_slack["my_app"].module.lambda.data.external.archive_prepare[0]: Read complete after 0s [id=-]
aws_autoscaling_notification.an["my_app"]: Creating...
module.notify_slack["my_app"].module.lambda.null_resource.archive[0]: Creating...
module.notify_slack["my_app"].module.lambda.null_resource.archive[0]: Provisioning with 'local-exec'...
module.notify_slack["my_app"].module.lambda.null_resource.archive[0] (local-exec): Executing: ["python3" ".terraform/modules/notify_slack.lambda/package.py" "build" "--timestamp" "1605787059469616800" "builds/5b24c39941d01dbddea733983e6a591d958660e6eeb0fcd7965098fb348aeeaa.plan.json"]
module.notify_slack["my_app"].module.lambda.null_resource.archive[0] (local-exec): Traceback (most recent call last):
module.notify_slack["my_app"].module.lambda.null_resource.archive[0] (local-exec):   File ".terraform/modules/notify_slack.lambda/package.py", line 1246, in <module>
module.notify_slack["my_app"].module.lambda.null_resource.archive[0] (local-exec):     main()
module.notify_slack["my_app"].module.lambda.null_resource.archive[0] (local-exec):   File ".terraform/modules/notify_slack.lambda/package.py", line 1242, in main
module.notify_slack["my_app"].module.lambda.null_resource.archive[0] (local-exec):     exit(args.command(args))
module.notify_slack["my_app"].module.lambda.null_resource.archive[0] (local-exec):   File ".terraform/modules/notify_slack.lambda/package.py", line 1113, in build_command
module.notify_slack["my_app"].module.lambda.null_resource.archive[0] (local-exec):     with open(args.build_plan_file) as f:
module.notify_slack["my_app"].module.lambda.null_resource.archive[0] (local-exec): FileNotFoundError: [Errno 2] No such file or directory: 'builds/5b24c39941d01dbddea733983e6a591d958660e6eeb0fcd7965098fb348aeeaa.plan.json'
aws_autoscaling_notification.an["my_app"]: Creation complete after 0s [id=arn:aws:sns:eu-west-1:380983831295:my_app]
Error: Error running command 'builds/5b24c39941d01dbddea733983e6a591d958660e6eeb0fcd7965098fb348aeeaa.plan.json': exit status 1. Output: Traceback (most recent call last):
  File ".terraform/modules/notify_slack.lambda/package.py", line 1246, in <module>
    main()
  File ".terraform/modules/notify_slack.lambda/package.py", line 1242, in main
    exit(args.command(args))
  File ".terraform/modules/notify_slack.lambda/package.py", line 1113, in build_command
    with open(args.build_plan_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'builds/5b24c39941d01dbddea733983e6a591d958660e6eeb0fcd7965098fb348aeeaa.plan.json'
```

**Comment by vdmkenny** [comment]
It must've been because of some partial apply in between, I deleted everything and recreated it, and now it works. Sorry!

**Comment by vdmkenny** [comment]
The same issue returned during the next `terraform apply` run. The initial creation is fine, then it throws this error every next time.

**Comment by mseest** [comment]
Any updates on this? I get the same error when doing `terraform apply`

**Comment by Crontis** [comment]
Same here, getting this issue running Terraform in Gitlab CI. It sometimes works after some/many retries..
Running `terraform apply`  locally on OS X works just fine.

**Comment by SimonRupar** [comment]
> OS

Same here. GitLab CI fails works locally on OS X. 
Terraform version: 1.0.3
Module version: 4.17.0

I set GitLab CI environment variable to :
`TF_RECREATE_MISSING_LAMBDA_PACKAGE` to `false` and this resolved my issue. More about it here: https://github.com/terraform-aws-modules/terraform-aws-lambda/issues/51#issuecomment-681978205
